<div id="project-box">
<h2>SpojGuide</h2>
<div id="project-content">
<b>Script Summary:</b>
This script helps you out in your perpetual search for the next SPOJ problem to solve! Works when you hunt for problems from another user's status page. It color codes problems based on the number of ACs, strikes out your solved problems in addition to some other tweaks.
</p>

<a style="float:right; margin:20px;" href="http://s3.amazonaws.com/uso_ss/13178/large.png?1311410730" rel="lightbox" title="SpojGuide in action - guiding you to your next solved problem!"><img alt="Thumb" src="http://s3.amazonaws.com/uso_ss/13178/thumb.png?1311410730"></a>

<ul><li>It color codes problems based on the number of ACs. It uses the following color scheme, can be changed easily in the code (try it!). Note that the colors are fuzzy and uses a simple linear interpolation. For example, a problem with AC count around ~300 will appear light green and one with AC count, say 50 will have some funny blue-violet color.   <br><br><table><tbody><tr><th>AC count</th><td> ~20 </td><td> ~30 </td><td> ~40 </td><td> ~80 </td><td> ~160 </td><td> 480+ </td></tr><tr><th>Color</th><td>Red</td><td>Pink</td><td>Purple</td><td>Blue</td><td>Green</td><td>No Hilight</td></tr></tbody></table></li>
<br/>
<li> Adds hover text on each problem code with number of ACs. </li><li> If you are logged in, strikes out the problems you have already solved. </li><li> Rewrites the problem links to the actual problem page instead of the user's status for the problem. </li></ul>



</div>
</div>

