          <h1>Characters</h1>

		      <a id="sketch" href="images/sketches/Skeleton_Ninja.png"><img alt="sketch" height="200px" src="images/sketches/Skeleton_Ninja.png" /></a>

          <hr> 

          <h1>Animals</h1>


		      <a id="sketch" href="images/sketches/Penguin.png"><img alt="sketch" height="120px" src="images/sketches/Penguin.png" /></a>
		      <a id="sketch" href="images/sketches/Giraffe.png"><img alt="sketch" height="120px" src="images/sketches/Giraffe.png" /></a>

		      <a id="sketch" href="images/sketches/Horse_Sketch.png"><img alt="sketch" height="80px" src="images/sketches/Horse_Sketch.png" /></a>
		      <a id="sketch" href="images/sketches/Wolf.png"><img alt="sketch" height="70px" src="images/sketches/Wolf.png" /></a>


          <hr> 

