<script>
  $(document).ready(function(){
          $("#dialog").dialog({
              autoOpen: false,
              modal: true
          });

          var fetchComments = function() {
              $.post('<?php echo $this->baseUrl("/index/fetch-scribbles")?>',
                     function(data){$('#post-list').html(data)});
          };

          $("button").button({icons: {primary: "ui-icon-circle-check"}});

          $('#submit-comment').click(function() {
                  $postid = <?php echo $this->blogpost->id ?>;
                  $comment = $('textarea#comment-comment').val();
                  if($comment == ''){
                      $("#dialog").dialog("open");
                      return false;
                  }
                  $user = $('input#comment-user').val();
                  if($user == '')
                      $user = 'Anonymous';
                  $url = $('input#comment-website').val();
                  $email = $('input#comment-email').val();
                  $.post('<?php echo $this->baseUrl("/blog/post-comment")?>',{
                              postid: $postid,
                              comment: $comment,
                              user: $user,
                              url: $url,
                              email: $email
                              }, function(data){
                          $('textarea,input').val('');

                  $.getJSON('<?php echo $this->baseUrl("/blog/fetch-comments")?>',{
                                 postid: <?php echo $this->blogpost->id ?>,
                              },function(data){
                                  $comments = 
'<div id="comment-box">'+
'<div id="comment">'+
data['comment'] +    
'</div>' +
'<div id="comment-end"><b>'+data['user']+'</b> on '+data['created']+'</div>'+
'</div>';

                          $('#comments').append($comments);
                      });
                      });

                  return false;
              });

      });
</script>
<h1><?php echo $this->blogpost->title?></h1>
<div id="postcontent">
     <?php echo $this->blogpost->content;?>
</div>
<div id="post-end">
     <a href="#leave-a-comment" class="leave-comment">Leave a Comment</a>
     <div class="right">
     <b>bloops</b> on <?php echo date("F j, Y \a\\t g:i a",strtotime($this->blogpost->created)) ?>
     </div>
</div>

<div id="comments">
<h1>Comments</h1>

<?php foreach ($this->comments as $comment): ?>
<div id="comment-box">
<div id="comment">
         <?php echo $this->escape($comment->comment) ?>
</div>
         <div id="comment-end"><b><?php echo $this->escape($comment->user)?></b> on  <?php echo date("F j, Y \a\\t g:i a",strtotime($comment->created)) ?></div>
</div>
 <?php endforeach ?>
</div>


<br/>
<br/>
<!--<img style="margin-top:-20px;float:left" src="/homepage/public/icons/comment2.jpg"/>-->
<h1 id="leave-a-comment">Leave a Comment</h1>
<div id="postcontent">
<input style="font-size: 15px; 1px 1px #ddd;" id="comment-user" type="text" placeholder="name">
<input style="font-size: 12px" id="comment-email" type="text" placeholder="email (optional, not published)">
<input style="font-size: 12px" id="comment-website" type="text" placeholder="website (optional)">
<textarea id="comment-comment" rows="5" placeholder="comment"></textarea>
<button id="submit-comment" style="font-size:12px">Submit Comment</button>
</div>

<br/><br/><br/><br/>

<div id="dialog" title="Empty Comment" style="font-size: 12px !important">
<br/>
Please write something in the comment box before submitting!
</div>