<ul>
  <li>
    <img class="icon" src="<?php echo $this->baseUrl('icons/color_128/pen.png')?>" />  
    Essay:<br>
    <a href="http://www.artofproblemsolving.com/Forum/viewtopic.php?f=133&t=280673">Math Experiences</a>
  </li>

  <li>
    <img class="icon" src="<?php echo $this->baseUrl('icons/color_128/book.png')?>" />                
    Short story:<br>
    <a href="http://razimanmistranslated.blogspot.com/2011/04/genie.html">Mistranslated: Genie</a>
  </li>
</ul>
