<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <title>Pencil and Paper</title>
  <head>
    <script src="<?php echo $this->baseUrl('jquery-1.6.4.min.js');?>"></script>
		<link type="text/css" href="<?php echo $this->baseUrl('css/custom-theme/jquery-ui-1.8.16.custom.css');?>" rel="stylesheet" />	
		<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery-ui-1.8.16.custom.min.js');?>"> </script>
    <link href="<?php echo $this->baseUrl('style.css');?>" rel="stylesheet" type="text/css">  
      <link rel="icon" 
            type="image/png" 
            href="<?php echo $this->baseUrl('icons/pencil2.png');?>">

     <link href="<?php echo $this->baseUrl('prettify/prettify.css');?>" type="text/css" rel="stylesheet" />
     <script type="text/javascript" src="<?php echo $this->baseUrl('prettify/prettify.js')?>"></script>
      </head>
    <body onload="prettyPrint()">

      <script>
        $(document).ready(function(){
        
        $('.dropdown').hide();        

        $('#admin').hover(function(){
         $('.dropdown').slideDown('fast').show();
        },function(){
         $('.dropdown').slideUp('fast').hide();
        });
        
        });
      </script>

     <div id="all">
        <div id="header">
          <img height="65px" src="<?php echo $this->baseUrl('icons/leafpad.png')?>" />
          <h1><a href=""> Pencil and Paper</a></h1> <br>

        </div>

     <?php
     $navlinks = array ( "index" => array("SCRIBBLES","icons/home.png"),
                         "blog" => array("BLOG","icons/diary.png"),
                         "problems" => array("PROBLEMS","icons/lightbulb.png"),
                         "sketches" => array("SKETCHES","icons/pencil.png"),
                         "projects" => array("PROJECTS","icons/gear.png"),
                         "writeups" => array("WRITEUPS","icons/pen.png"),
                         "about" => array("ABOUT","icons/info.png"),
                      );
     $page = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
     ?>


		    <div id="navbar">


					<ul id="nav">
         <?php 
         foreach ($navlinks as $link => $data) {
         echo '<li><a id="'.$link.'" href="'. $this->baseUrl($link).'"';
         if ($page == $link)
             echo ' class="current"';
             echo '><img src="'.$this->baseUrl($data[1]).'"/>'.$data[0].'</a></li>';
         }
         ?>
         <?php 
        if(Zend_Auth::getInstance()->hasIdentity())
          echo 
         '<li id="admin">'.
         '<a href=""><img src="'.$this->baseUrl('icons/color_18/screwdriver.png').'"/>ADMIN</a>'.
         '<ul class="dropdown">'.
         '<li><a class="drop" href="'.$this->baseUrl('index/problems/admin').'">Problems</a></li>'.
         '<li><a class="drop" href="'.$this->baseUrl('index/admin').'">Scribbles</a></li>'.
         '<li><a class="drop" href="'.$this->baseUrl('blog/admin').'">Blog</a></li>'.
         '<li><a class="drop" href="'.$this->baseUrl('writeups/admin').'">Writeups</a></li>'.
         '<li><a class="drop" href="'.$this->baseUrl('index/admin-updates').'">Updates</a></li>'.
         '<li><a class="drop" href="'.$this->baseUrl('auth/logout').'">Logout</a></li>'.
         '</ul>';

        ?>
           </li>
					</ul>
		    </div>
        <div id="content">



      
        <?php echo $this->layout()->content; ?>

          </div> <!-- end content -->

          <div id="sidebar">
         <br>

<?php echo $this->action('recent', 'index'); ?>
         
         <br>

            <h1>LINKS</h1>
<?php echo $this->action('links', 'index'); ?>


            
            </div>

          <div id="footer">
	          <p>Copyright &copy 2011 Anudhyan Boral</p>
          </div>

        </div> <!-- end all -->

      </body>
