          <h1>About</h1>
<div id="postcontent">
          <img style="float: left; padding: 20px;" src="icons/color_128/user.png" /> 
          <p>Hi, I am  Anudhyan Boral. I am currently doing my Bachelors in Mathematics and Computer Science at <a href="http://cmi.ac.in">Chennai Mathematical Institute</a>. When I'm not using my real name, I go by the handle of <a href="#bloops">bloops</a>.</p>
          <p>I am passionate about programming. I solve problems at Topcoder, Codeforces and occasionally Spoj. <span title="You could have figured this out"></span> I also <a href=""> sketch</a>, paint and play the violin when no one's looking. I update my <a href="/homepage/public/index">homepage</a> as frequently as people visit it.</p><br>
</div>
<hr> 

          <h1>Drop me an email</h1>
<div id="postcontent">
          &nbsp&nbsp<img style="height: 30px;" src="icons/color_128/mail.png" />
           &nbsp&nbsp<img  style=" vertical-align: 20%" title="spambots begone" src="icons/email.png"/>          
          <br><br><hr>
</div>
